# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mysql
#   namespace: books
# data:
#   MYSQL_HOST: "mysql"
#   #MYSQL_USER: "root"
#   MYSQL_PASSWORD: "root"
#   MYSQL_DATABASE: "lms"
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql
#   namespace: books
# type: Opaque
# data:
#   MYSQL_ROOT_PASSWORD: cm9vdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: books
  labels: # these labels are deployment labels
    app: mysql
    project: books
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: mysql
      project: books
      tier: db
  template:
    metadata:
      labels: # these labels are pod labels
        app: mysql
        project: books
        tier: db
    spec:
      containers:
      - name: mysql
        image: suryashankar598/mysql:latest
        #imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql
        - secretRef:
            name: mysql
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   namespace: books
# spec:
#   selector:
#     app: mysql
#     project: books
#     tier: db
#   ports:
#   - protocol: TCP
#     port: 3306 #service-port
#     targetPort: 3306 #container-port