apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: books
spec:
  selector:
    app: mysql
    project: books
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #container-port